# action.yml
name: 'Dassana IaC GitHub Action'
author: 'Dassana'
description: 'Supercharge your IaC checks to get to production faster'
inputs:
  aws_region:
    description: 'Region cloudformation stack is deployed in'
    required: true
  bucket_name:
    description: 'S3 bucket to house CFT file'
    required: true
  stack_name:
    description: 'Cloudformation stack name'
    required: true
  template_file:
    description: 'Path to CFT file'
    required: true
    
branding:
  icon: 'arrow-left'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: python-test
        uses: actions/setup-python@v2.2.2
        with: 
          python-version: 3.8
      - shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install requests
          pip install checkov
          pip install pandas
          pip install tabulate
      - shell: bash
        run: |
          python ./check_changes.py
        env:
          INPUT_AWS_REGION: ${{ inputs.aws_region }}
          INPUT_BUCKET_NAME: ${{ inputs.bucket_name }}
          INPUT_STACK_NAME : ${{ inputs.stack_name }}
          INPUT_TEMPLATE_FILE : ${{ inputs.template_file }}
        
