# action.yml
name: 'Dassana IaC GitHub Action'
author: 'Dassana'
description: 'Supercharge your IaC checks to get to production faster'
inputs:
  github_token:
    description: 'Github PAT'
    required: true
  aws_region:
    description: 'Region cloudformation stack is deployed in'
    required: true
  bucket_name:
    description: 'S3 bucket to house CFT file'
    required: true
  stack_name:
    description: 'Cloudformation stack name'
    required: true
  template_file:
    description: 'Path to CFT file'
    required: true
  aws_access_key_id:
    description: 'Access Key ID for user created by CFT'
    required: true
  aws_secret_access_key:
    description: 'Secret Access Key for user created by CFT'
    required: true
  api_gateway_endpoint:
    description: 'Dassana API endpoint url'
    required: true
  api_key:
    description: 'Dassana API endpoint key'
    required: true
    
branding:
  icon: 'arrow-left'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: python-test
        uses: actions/setup-python@v2.2.2
        with: 
          python-version: 3.8
      - shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install requests
          pip install checkov
          pip install pandas
          pip install tabulate
      - shell: bash
        run: |
          python ./check_changes.py
        env:
          GITHUB_PR: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ inputs.github_token }}
          INPUT_AWS_REGION: ${{ inputs.aws_region }}
          INPUT_BUCKET_NAME: ${{ inputs.bucket_name }}
          INPUT_STACK_NAME : ${{ inputs.stack_name }}
          INPUT_TEMPLATE_FILE : ${{ inputs.template_file }}
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
          API_GATEWAY_ENDPOINT: ${{ inputs.api_gateway_endpoint }}
          API_KEY: ${{ inputs.api_key }}
        
