# action.yml
name: 'Dassana IaC GitHub Action'
author: 'Dassana'
description: 'Supercharge your IaC checks to get to production faster'
inputs:
  aws_region:
    description: 'Region cloudformation stack is deployed in'
    required: true
  bucket_name:
    description: 'S3 bucket to house CFT file'
    required: true
  stack_name:
    description: 'Cloudformation stack name'
    required: true
  template_file:
    description: 'Path to CFT file'
    required: false

branding:
  icon: 'arrow-left'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: python-test
        uses: actions/setup-python@v2.2.2
        with: 
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install requests
          pip install checkov
          pip install pandas
          pip install tabulate
      - name: Create and Analyze Change Set
        run: |
          python ./check_changes.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR: ${{ github.event.number }}
          AWS_DEFAULT_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          API_GATEWAY_ENDPOINT: ${{ secrets.API_GATEWAY_ENDPOINT }}
          API_KEY: ${{ secrets.API_KEY }}
